#url: http://localhost:4000    # l'url finale de votre site. Elle est utilisée dans la variable site.url
baseurl: /SitePC_Chaptal
#url: #http://marineflower.github.io/SitePC_Chaptal
name: Physique, PC*, Chaptal, 15-16
markdown: kramdown #rdiscount           # le parseur de Markdown à utiliser pour parser vos fichiers. La syntaxe Markdown peut changer suivant le parseur utilisé
paginate: 5                   # le nombre d'articles à afficher par page
paginate_path: /blog/page:num # l'url générée pour la pagination
#permalink: date #/blog/:title       # l'url générée pour la visualisation d'un article complet
